---
abstract: 'Compiles a MOF file'
author:
  - 'Stephen James Hurd <shurd@broadcom.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DMTF-CIM-MOF
no_index:
  directory:
    - t
    - inc
requires:
  DMTF::CIM: 0
  Exporter: 5.57
  Storable: 0
  Test::More: 0
  version: 0
version: v0.5.0
